"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const App_1 = require("./App");
const Bike_1 = require("./Bike");
const User_1 = require("./User");
const bike = new Bike_1.Bike('mountain bike', 'mountain', 123, 500, 100.5, 'desc', 5, []);
const user = new User_1.User('Maria', 'maria@mail.com', '1234');
const today = new Date();
const twoDaysFromToday = new Date();
twoDaysFromToday.setDate(twoDaysFromToday.getDate() + 2);
const tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
const sevenDaysFromToday = new Date();
sevenDaysFromToday.setDate(sevenDaysFromToday.getDate() + 7);
const app = new App_1.App();
app.registerUser(user);
console.log(app.findUser('maria@mail.com'));
app.registerBike(bike);
console.log(bike);
const rent = app.rentBike(bike, user, today, tomorrow);
console.log(rent);
const returnedRent = app.returnBike(rent, twoDaysFromToday);
console.log(returnedRent);
app.removeUser(user);
console.log(app.findUser('maria@mail.com'));
